# Generated by Django 3.2.9 on 2021-12-05 19:22

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('amount', models.IntegerField(verbose_name=django.db.models.aggregates.Min(1))),
                ('delivery_time', models.IntegerField(verbose_name=django.db.models.aggregates.Min(1))),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
