# Generated by Django 3.2.9 on 2021-12-21 11:57

from django.db import migrations, models
import django.db.models.deletion
import storage_service.validators


class Migration(migrations.Migration):

    dependencies = [
        ('storage_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage_service.product')),
                ('name', models.CharField(max_length=64)),
                ('base_price', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
                ('weight', models.FloatField()),
                ('category', models.CharField(max_length=32)),
            ],
            bases=('storage_service.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(validators=[storage_service.validators.validate_higher_or_equals_one]),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.IntegerField(validators=[storage_service.validators.validate_higher_or_equals_one]),
        ),
    ]
