name: Workflow Staging
on:
  push:
      branches:
        - main
jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - name: Build Docker Image
        run: docker build -t registry.heroku.com/${{ secrets.APP_NAME }}/web .
      - name: Push Docker Container
        run: docker push registry.heroku.com/${{ secrets.APP_NAME }}/web 
      - name: Release Image
        run: heroku container:release -a ${{ secrets.APP_NAME }} web