name: Workflow
on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./boilerplate/requirements.txt
      - run: python ./boilerplate/manage.py test
  deploy-to-heroku:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./boilerplate/requirements.txt
      - name: Login to Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - name: Build Docker Image
        run: docker build -t registry.heroku.com/${{ secrets.APP_NAME }}/web .
      - name: Push Docker Container
        run: docker push registry.heroku.com/${{ secrets.APP_NAME }}/web 
      - name: Release Image
        run: heroku container:release -a ${{ secrets.APP_NAME }} web